pipeline {

    agent {
        node {
            label 'AGENT-1'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters {

        string(name: 'Action', defaultValue: '', description: 'Perform Terraform apply?')

    }

    stages{

        stage("init"){
            steps{
                sh """
                    cd aws_vpc
                    terraform init -reconfigure
                """
            }
        }

        stage("plan"){
            steps{
                sh """
                    cd aws_vpc
                    terraform plan
                """
            }
        }
        stage("apply"){
            when {
                expression {
                    params.Action == 'apply'
                }
            }
            steps {
                sh """
                    cd aws_vpc
                    terraform apply -auto-approve
                """
            }
        }
        stage("destroy"){
            
            steps {
                sleep 300
                sh """
                    cd aws_vpc
                    terraform destroy -auto-approve
                """
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}