pipeline {

    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment {
        packageVersion = ''
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages{

        stage("Get Version"){
            steps{
                script {
                    def packageJson = readJSON file: './package.json'
                    packageVersion = packageJson.version
                    echo "version $packageVersion"
                }
            }
        }

        stage("Test"){

            steps{
                echo "Testing"
            }

        }

        stage("Deploy"){

            steps {
                echo "Deploy"
            }

        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}